#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ynab_auto_budget

Uses a budget template and the You Need a Budget (YNAB) API to suggest monthy
budget amounts. The YNAB currently does not support writing monthly budget
amounts, so that must be done manually.
"""

import sys
import os
import argparse
import json

import ynab
import yaml


class YNABAutoBudgetError(Exception):
    """ Used for exceptions specific to this script """

    pass


class YNABAutoBudget:
    def __init__(self, credentials_filename):
        self.__setup_ynab(credentials_filename)
        self.__get_ynab_budget_categories()
        self.__remove_hidden_categories()
        self.__remove_unused_category_groups()

    def __setup_ynab(self, credentials_filename):
        """ Get the user's credentials """

        self.configuration = ynab.Configuration()

        try:
            with open(os.path.expanduser(credentials_filename)) as cfile:
                credentials = json.load(cfile)

            self.configuration.api_key['Authorization'] = credentials['key']
            self.configuration.api_key_prefix['Authorization'] = credentials['prefix']
        except IOError as err:
            raise YNABAutoBudgetError('Unable to open credentials file:\n{}'\
                                    .format(err))
        except json.JSONDecodeError:
            raise YNABAutoBudgetError('Unable to parse credentials file {}'\
                                    .format(credentials_filename))
        except KeyError as err:
            raise YNABAutoBudgetError('Expected key {} not found in credentials '\
                                    'file {}'.format(err, credentials_filename))


    def __get_ynab_budget_id(self, name):
        """ Get the API id for the named budget """

        api = ynab.BudgetsApi()

        try:
            budget_summary = api.get_budgets()
        except ynab.rest.ApiException as err:
            raise YNABAutoBudgetError('YNAB API error:\n{}'.format(err))

        # Find the named budget and retur the ID
        for budget in budget_summary.data.budgets:
            if budget.name == name:
                return budget.id

        # If we get here, the budget wasn't found
        raise YNABAutoBudgetError("Budget '{}' not found")


    def __get_ynab_budget_categories(self):
        """ Get the catagory names from the budget """

        budget_id = self.__get_ynab_budget_id('My Budget')

        api = ynab.CategoriesApi()

        try:
            categories_response = api.get_categories(budget_id)
        except ynab.rest.ApiException as err:
            raise YNABAutoBudgetError('YNAB API error:\n{}'.format(err))

        self.category_groups = categories_response.data.category_groups


    def __remove_hidden_categories(self):
        for group in self.category_groups:
            group.categories = list(filter(lambda x: not x.hidden, group.categories))


    @staticmethod
    def __valid_category_group(group):
        return group.categories and group.name != 'Internal Master Category'


    def __remove_unused_category_groups(self):
        self.category_groups = list(filter(YNABAutoBudget.__valid_category_group, self.category_groups))


    def create_empty_template(self, filename):
        """ Create an empty template file """

        if os.path.exists(filename):
            raise YNABAutoBudgetError('{} already exists, will not overwrite'.format(filename))

        template = {'remainder': None, 'categories': []}

        for group in self.category_groups:
            for category in group.categories:
                if not category.hidden:
                    template['categories'].append({'category': category.name,
                                                'type': 'fixed',
                                                'value': 0})

        try:
            with open(filename,'w') as tfile:
                yaml.dump(template, stream=tfile, default_flow_style=False)
        except IOError as err:
            raise YNABAutoBudgetError(err)


    def show_current_values(self):
        for group in self.category_groups:
            #print(group)
            print(group.name)

            for category in group.categories:
                print('  {}: Budgeted {:.2f} Activity {:.2f} Balance {:.2f}'\
                    .format(category.name,
                            category.budgeted / 1000.0,
                            category.activity / 1000.0,
                            category.balance / 1000.0))
        
        #print(groups)


def main(arguments):
    """ Get YNAB budget, template, and display results """

    try:
        auto_budget = YNABAutoBudget(arguments.credentials)

        if args.create:
            auto_budget.create_empty_template(arguments.template)
        elif args.show:
            auto_budget.show_current_values()

    except YNABAutoBudgetError as err:
        print(err)
        return 1

    return 0

if __name__ == '__main__':
    # Parse arguments with argparse
    formatter_class = argparse.ArgumentDefaultsHelpFormatter

    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=formatter_class)

    parser.add_argument('template',
                        help="Budget template file",
                        type=str)

    parser.add_argument('-c', '--credentials',
                        help="YNAB credentials file",
                        default='~/.ynab/ynab_credentials.json',
                        type=str)
    
    parser.add_argument('--create',
                        help='Create empty template',
                        action='store_true')

    parser.add_argument('-s', '--show',
                        help='Show current budgeted values',
                        action='store_true')

    args = parser.parse_args(sys.argv[1:])

    # Call main() with parsed args
    sys.exit(main(args))
